### ISSUE TITLE
Remove Unused Components

### ISSUE THREAD

**Issue by George-Madeley** [Bath-Biodevices-Without-Borders/Website#6]
# Remove Unused Components

## Problem

There are a series of images, components, styles and more that are not being used anywhere within the application. These increase the size of the application causing increased download times when someone attempts to access the website.

## How To Solve

Investigate what files are not being referenced anywhere within the website and delete them. Ensure deleting the file does not cause any errors throughout the website.

**Comment by anjisthebest** [comment]
deleted unused files and checked to make sure website is still working properly
